/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as TestSuitesRouteImport } from './routes/test-suites'
import { Route as RagsRouteImport } from './routes/rags'
import { Route as QuotasRouteImport } from './routes/quotas'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LlmsRouteImport } from './routes/llms'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as FinopsRouteImport } from './routes/finops'
import { Route as DatasetsRouteImport } from './routes/datasets'
import { Route as DatabasesRouteImport } from './routes/databases'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConversationsRouteImport } from './routes/conversations'
import { Route as ApisRouteImport } from './routes/apis'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates.index'
import { Route as OrchestrationsIndexRouteImport } from './routes/orchestrations.index'
import { Route as ExecutionsIndexRouteImport } from './routes/executions.index'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as OrchestrationsNewRouteImport } from './routes/orchestrations.new'
import { Route as AgentsNewRouteImport } from './routes/agents.new'
import { Route as OrchestrationsIdIndexRouteImport } from './routes/orchestrations.$id.index'
import { Route as AgentsIdIndexRouteImport } from './routes/agents.$id.index'
import { Route as OrchestrationsIdEditRouteImport } from './routes/orchestrations.$id.edit'
import { Route as AgentsIdEditRouteImport } from './routes/agents.$id.edit'

const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const TestSuitesRoute = TestSuitesRouteImport.update({
  id: '/test-suites',
  path: '/test-suites',
  getParentRoute: () => rootRouteImport,
} as any)
const RagsRoute = RagsRouteImport.update({
  id: '/rags',
  path: '/rags',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotasRoute = QuotasRouteImport.update({
  id: '/quotas',
  path: '/quotas',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsRoute = LlmsRouteImport.update({
  id: '/llms',
  path: '/llms',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const FinopsRoute = FinopsRouteImport.update({
  id: '/finops',
  path: '/finops',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsRoute = DatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabasesRoute = DatabasesRouteImport.update({
  id: '/databases',
  path: '/databases',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsRoute = ConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApisRoute = ApisRouteImport.update({
  id: '/apis',
  path: '/apis',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrchestrationsIndexRoute = OrchestrationsIndexRouteImport.update({
  id: '/orchestrations/',
  path: '/orchestrations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutionsIndexRoute = ExecutionsIndexRouteImport.update({
  id: '/executions/',
  path: '/executions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrchestrationsNewRoute = OrchestrationsNewRouteImport.update({
  id: '/orchestrations/new',
  path: '/orchestrations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsNewRoute = AgentsNewRouteImport.update({
  id: '/agents/new',
  path: '/agents/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OrchestrationsIdIndexRoute = OrchestrationsIdIndexRouteImport.update({
  id: '/orchestrations/$id/',
  path: '/orchestrations/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIdIndexRoute = AgentsIdIndexRouteImport.update({
  id: '/agents/$id/',
  path: '/agents/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrchestrationsIdEditRoute = OrchestrationsIdEditRouteImport.update({
  id: '/orchestrations/$id/edit',
  path: '/orchestrations/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIdEditRoute = AgentsIdEditRouteImport.update({
  id: '/agents/$id/edit',
  path: '/agents/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/apis': typeof ApisRoute
  '/conversations': typeof ConversationsRoute
  '/dashboard': typeof DashboardRoute
  '/databases': typeof DatabasesRoute
  '/datasets': typeof DatasetsRoute
  '/finops': typeof FinopsRoute
  '/knowledge': typeof KnowledgeRoute
  '/llms': typeof LlmsRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/playground': typeof PlaygroundRoute
  '/quotas': typeof QuotasRoute
  '/rags': typeof RagsRoute
  '/test-suites': typeof TestSuitesRoute
  '/training': typeof TrainingRoute
  '/agents/new': typeof AgentsNewRoute
  '/orchestrations/new': typeof OrchestrationsNewRoute
  '/agents/': typeof AgentsIndexRoute
  '/executions/': typeof ExecutionsIndexRoute
  '/orchestrations/': typeof OrchestrationsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/agents/$id/edit': typeof AgentsIdEditRoute
  '/orchestrations/$id/edit': typeof OrchestrationsIdEditRoute
  '/agents/$id/': typeof AgentsIdIndexRoute
  '/orchestrations/$id/': typeof OrchestrationsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/apis': typeof ApisRoute
  '/conversations': typeof ConversationsRoute
  '/dashboard': typeof DashboardRoute
  '/databases': typeof DatabasesRoute
  '/datasets': typeof DatasetsRoute
  '/finops': typeof FinopsRoute
  '/knowledge': typeof KnowledgeRoute
  '/llms': typeof LlmsRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/playground': typeof PlaygroundRoute
  '/quotas': typeof QuotasRoute
  '/rags': typeof RagsRoute
  '/test-suites': typeof TestSuitesRoute
  '/training': typeof TrainingRoute
  '/agents/new': typeof AgentsNewRoute
  '/orchestrations/new': typeof OrchestrationsNewRoute
  '/agents': typeof AgentsIndexRoute
  '/executions': typeof ExecutionsIndexRoute
  '/orchestrations': typeof OrchestrationsIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/agents/$id/edit': typeof AgentsIdEditRoute
  '/orchestrations/$id/edit': typeof OrchestrationsIdEditRoute
  '/agents/$id': typeof AgentsIdIndexRoute
  '/orchestrations/$id': typeof OrchestrationsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/apis': typeof ApisRoute
  '/conversations': typeof ConversationsRoute
  '/dashboard': typeof DashboardRoute
  '/databases': typeof DatabasesRoute
  '/datasets': typeof DatasetsRoute
  '/finops': typeof FinopsRoute
  '/knowledge': typeof KnowledgeRoute
  '/llms': typeof LlmsRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/playground': typeof PlaygroundRoute
  '/quotas': typeof QuotasRoute
  '/rags': typeof RagsRoute
  '/test-suites': typeof TestSuitesRoute
  '/training': typeof TrainingRoute
  '/agents/new': typeof AgentsNewRoute
  '/orchestrations/new': typeof OrchestrationsNewRoute
  '/agents/': typeof AgentsIndexRoute
  '/executions/': typeof ExecutionsIndexRoute
  '/orchestrations/': typeof OrchestrationsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/agents/$id/edit': typeof AgentsIdEditRoute
  '/orchestrations/$id/edit': typeof OrchestrationsIdEditRoute
  '/agents/$id/': typeof AgentsIdIndexRoute
  '/orchestrations/$id/': typeof OrchestrationsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/apis'
    | '/conversations'
    | '/dashboard'
    | '/databases'
    | '/datasets'
    | '/finops'
    | '/knowledge'
    | '/llms'
    | '/login'
    | '/mcp'
    | '/playground'
    | '/quotas'
    | '/rags'
    | '/test-suites'
    | '/training'
    | '/agents/new'
    | '/orchestrations/new'
    | '/agents/'
    | '/executions/'
    | '/orchestrations/'
    | '/templates/'
    | '/agents/$id/edit'
    | '/orchestrations/$id/edit'
    | '/agents/$id/'
    | '/orchestrations/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/apis'
    | '/conversations'
    | '/dashboard'
    | '/databases'
    | '/datasets'
    | '/finops'
    | '/knowledge'
    | '/llms'
    | '/login'
    | '/mcp'
    | '/playground'
    | '/quotas'
    | '/rags'
    | '/test-suites'
    | '/training'
    | '/agents/new'
    | '/orchestrations/new'
    | '/agents'
    | '/executions'
    | '/orchestrations'
    | '/templates'
    | '/agents/$id/edit'
    | '/orchestrations/$id/edit'
    | '/agents/$id'
    | '/orchestrations/$id'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/apis'
    | '/conversations'
    | '/dashboard'
    | '/databases'
    | '/datasets'
    | '/finops'
    | '/knowledge'
    | '/llms'
    | '/login'
    | '/mcp'
    | '/playground'
    | '/quotas'
    | '/rags'
    | '/test-suites'
    | '/training'
    | '/agents/new'
    | '/orchestrations/new'
    | '/agents/'
    | '/executions/'
    | '/orchestrations/'
    | '/templates/'
    | '/agents/$id/edit'
    | '/orchestrations/$id/edit'
    | '/agents/$id/'
    | '/orchestrations/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  ApisRoute: typeof ApisRoute
  ConversationsRoute: typeof ConversationsRoute
  DashboardRoute: typeof DashboardRoute
  DatabasesRoute: typeof DatabasesRoute
  DatasetsRoute: typeof DatasetsRoute
  FinopsRoute: typeof FinopsRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LlmsRoute: typeof LlmsRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  PlaygroundRoute: typeof PlaygroundRoute
  QuotasRoute: typeof QuotasRoute
  RagsRoute: typeof RagsRoute
  TestSuitesRoute: typeof TestSuitesRoute
  TrainingRoute: typeof TrainingRoute
  AgentsNewRoute: typeof AgentsNewRoute
  OrchestrationsNewRoute: typeof OrchestrationsNewRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  ExecutionsIndexRoute: typeof ExecutionsIndexRoute
  OrchestrationsIndexRoute: typeof OrchestrationsIndexRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  AgentsIdEditRoute: typeof AgentsIdEditRoute
  OrchestrationsIdEditRoute: typeof OrchestrationsIdEditRoute
  AgentsIdIndexRoute: typeof AgentsIdIndexRoute
  OrchestrationsIdIndexRoute: typeof OrchestrationsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-suites': {
      id: '/test-suites'
      path: '/test-suites'
      fullPath: '/test-suites'
      preLoaderRoute: typeof TestSuitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rags': {
      id: '/rags'
      path: '/rags'
      fullPath: '/rags'
      preLoaderRoute: typeof RagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotas': {
      id: '/quotas'
      path: '/quotas'
      fullPath: '/quotas'
      preLoaderRoute: typeof QuotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms': {
      id: '/llms'
      path: '/llms'
      fullPath: '/llms'
      preLoaderRoute: typeof LlmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finops': {
      id: '/finops'
      path: '/finops'
      fullPath: '/finops'
      preLoaderRoute: typeof FinopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets': {
      id: '/datasets'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof DatasetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/databases': {
      id: '/databases'
      path: '/databases'
      fullPath: '/databases'
      preLoaderRoute: typeof DatabasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations': {
      id: '/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof ConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apis': {
      id: '/apis'
      path: '/apis'
      fullPath: '/apis'
      preLoaderRoute: typeof ApisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orchestrations/': {
      id: '/orchestrations/'
      path: '/orchestrations'
      fullPath: '/orchestrations/'
      preLoaderRoute: typeof OrchestrationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executions/': {
      id: '/executions/'
      path: '/executions'
      fullPath: '/executions/'
      preLoaderRoute: typeof ExecutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orchestrations/new': {
      id: '/orchestrations/new'
      path: '/orchestrations/new'
      fullPath: '/orchestrations/new'
      preLoaderRoute: typeof OrchestrationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/new': {
      id: '/agents/new'
      path: '/agents/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AgentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orchestrations/$id/': {
      id: '/orchestrations/$id/'
      path: '/orchestrations/$id'
      fullPath: '/orchestrations/$id/'
      preLoaderRoute: typeof OrchestrationsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$id/': {
      id: '/agents/$id/'
      path: '/agents/$id'
      fullPath: '/agents/$id/'
      preLoaderRoute: typeof AgentsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orchestrations/$id/edit': {
      id: '/orchestrations/$id/edit'
      path: '/orchestrations/$id/edit'
      fullPath: '/orchestrations/$id/edit'
      preLoaderRoute: typeof OrchestrationsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$id/edit': {
      id: '/agents/$id/edit'
      path: '/agents/$id/edit'
      fullPath: '/agents/$id/edit'
      preLoaderRoute: typeof AgentsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  ApisRoute: ApisRoute,
  ConversationsRoute: ConversationsRoute,
  DashboardRoute: DashboardRoute,
  DatabasesRoute: DatabasesRoute,
  DatasetsRoute: DatasetsRoute,
  FinopsRoute: FinopsRoute,
  KnowledgeRoute: KnowledgeRoute,
  LlmsRoute: LlmsRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  PlaygroundRoute: PlaygroundRoute,
  QuotasRoute: QuotasRoute,
  RagsRoute: RagsRoute,
  TestSuitesRoute: TestSuitesRoute,
  TrainingRoute: TrainingRoute,
  AgentsNewRoute: AgentsNewRoute,
  OrchestrationsNewRoute: OrchestrationsNewRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  ExecutionsIndexRoute: ExecutionsIndexRoute,
  OrchestrationsIndexRoute: OrchestrationsIndexRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
  AgentsIdEditRoute: AgentsIdEditRoute,
  OrchestrationsIdEditRoute: OrchestrationsIdEditRoute,
  AgentsIdIndexRoute: AgentsIdIndexRoute,
  OrchestrationsIdIndexRoute: OrchestrationsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
