/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RagsRouteImport } from './routes/rags'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LlmsRouteImport } from './routes/llms'
import { Route as ApisRouteImport } from './routes/apis'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrchestrationsIdRouteImport } from './routes/orchestrations.$id'
import { Route as AgentsIdRouteImport } from './routes/agents.$id'
import { Route as OrchestrationsIdEditRouteImport } from './routes/orchestrations.$id.edit'
import { Route as AgentsIdEditRouteImport } from './routes/agents.$id.edit'

const RagsRoute = RagsRouteImport.update({
  id: '/rags',
  path: '/rags',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsRoute = LlmsRouteImport.update({
  id: '/llms',
  path: '/llms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApisRoute = ApisRouteImport.update({
  id: '/apis',
  path: '/apis',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrchestrationsIdRoute = OrchestrationsIdRouteImport.update({
  id: '/orchestrations/$id',
  path: '/orchestrations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIdRoute = AgentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AgentsRoute,
} as any)
const OrchestrationsIdEditRoute = OrchestrationsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => OrchestrationsIdRoute,
} as any)
const AgentsIdEditRoute = AgentsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AgentsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/apis': typeof ApisRoute
  '/llms': typeof LlmsRoute
  '/mcp': typeof McpRoute
  '/rags': typeof RagsRoute
  '/agents/$id': typeof AgentsIdRouteWithChildren
  '/orchestrations/$id': typeof OrchestrationsIdRouteWithChildren
  '/agents/$id/edit': typeof AgentsIdEditRoute
  '/orchestrations/$id/edit': typeof OrchestrationsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/apis': typeof ApisRoute
  '/llms': typeof LlmsRoute
  '/mcp': typeof McpRoute
  '/rags': typeof RagsRoute
  '/agents/$id': typeof AgentsIdRouteWithChildren
  '/orchestrations/$id': typeof OrchestrationsIdRouteWithChildren
  '/agents/$id/edit': typeof AgentsIdEditRoute
  '/orchestrations/$id/edit': typeof OrchestrationsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/apis': typeof ApisRoute
  '/llms': typeof LlmsRoute
  '/mcp': typeof McpRoute
  '/rags': typeof RagsRoute
  '/agents/$id': typeof AgentsIdRouteWithChildren
  '/orchestrations/$id': typeof OrchestrationsIdRouteWithChildren
  '/agents/$id/edit': typeof AgentsIdEditRoute
  '/orchestrations/$id/edit': typeof OrchestrationsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/apis'
    | '/llms'
    | '/mcp'
    | '/rags'
    | '/agents/$id'
    | '/orchestrations/$id'
    | '/agents/$id/edit'
    | '/orchestrations/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/apis'
    | '/llms'
    | '/mcp'
    | '/rags'
    | '/agents/$id'
    | '/orchestrations/$id'
    | '/agents/$id/edit'
    | '/orchestrations/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/apis'
    | '/llms'
    | '/mcp'
    | '/rags'
    | '/agents/$id'
    | '/orchestrations/$id'
    | '/agents/$id/edit'
    | '/orchestrations/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRouteWithChildren
  ApisRoute: typeof ApisRoute
  LlmsRoute: typeof LlmsRoute
  McpRoute: typeof McpRoute
  RagsRoute: typeof RagsRoute
  OrchestrationsIdRoute: typeof OrchestrationsIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rags': {
      id: '/rags'
      path: '/rags'
      fullPath: '/rags'
      preLoaderRoute: typeof RagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms': {
      id: '/llms'
      path: '/llms'
      fullPath: '/llms'
      preLoaderRoute: typeof LlmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apis': {
      id: '/apis'
      path: '/apis'
      fullPath: '/apis'
      preLoaderRoute: typeof ApisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orchestrations/$id': {
      id: '/orchestrations/$id'
      path: '/orchestrations/$id'
      fullPath: '/orchestrations/$id'
      preLoaderRoute: typeof OrchestrationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$id': {
      id: '/agents/$id'
      path: '/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AgentsIdRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/orchestrations/$id/edit': {
      id: '/orchestrations/$id/edit'
      path: '/edit'
      fullPath: '/orchestrations/$id/edit'
      preLoaderRoute: typeof OrchestrationsIdEditRouteImport
      parentRoute: typeof OrchestrationsIdRoute
    }
    '/agents/$id/edit': {
      id: '/agents/$id/edit'
      path: '/edit'
      fullPath: '/agents/$id/edit'
      preLoaderRoute: typeof AgentsIdEditRouteImport
      parentRoute: typeof AgentsIdRoute
    }
  }
}

interface AgentsIdRouteChildren {
  AgentsIdEditRoute: typeof AgentsIdEditRoute
}

const AgentsIdRouteChildren: AgentsIdRouteChildren = {
  AgentsIdEditRoute: AgentsIdEditRoute,
}

const AgentsIdRouteWithChildren = AgentsIdRoute._addFileChildren(
  AgentsIdRouteChildren,
)

interface AgentsRouteChildren {
  AgentsIdRoute: typeof AgentsIdRouteWithChildren
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsIdRoute: AgentsIdRouteWithChildren,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface OrchestrationsIdRouteChildren {
  OrchestrationsIdEditRoute: typeof OrchestrationsIdEditRoute
}

const OrchestrationsIdRouteChildren: OrchestrationsIdRouteChildren = {
  OrchestrationsIdEditRoute: OrchestrationsIdEditRoute,
}

const OrchestrationsIdRouteWithChildren =
  OrchestrationsIdRoute._addFileChildren(OrchestrationsIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRouteWithChildren,
  ApisRoute: ApisRoute,
  LlmsRoute: LlmsRoute,
  McpRoute: McpRoute,
  RagsRoute: RagsRoute,
  OrchestrationsIdRoute: OrchestrationsIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
